#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: "Nica EcoComputación"  # The title of the book
author: Emilio Mayorga
copyright: "2021"  # Copyright year to be placed in the footer
logo: imagenes/EVIMap_MonthlyClimatology_April_70pct.jpeg  # A path to the book logo
description: >-
  Datos y computacion ambiental de Nicaragua

html:
  baseurl: https://emiliom.github.io/nica-ecocomputacion/
  favicon: imagenes/favicon1.ico
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

repository:
  url: https://github.com/emiliom/nica-ecocomputacion
  branch: master
  path_to_book: libro

sphinx:
  config:
    language: es

# General execution settings
only_build_toc_files: true

parse:
  myst_extended_syntax: true

execute:
  execute_notebooks: auto
  exclude_patterns:
    # Cuadernos en desarrollo
    - '_desar_*'
